---
development:
  BIGQUERY_PROJECT: weather-weaver
  BIGQUERY_DATASET: dev_forecasts
  BIGQUERY_DAILY_TABLE: daily
  BIGQUERY_HOURLY_TABLE: hourly
  LOCATIONS:
    - loc_id: TAIPEI-1
      latitude: 25.0402779
      longitude: 121.5301837
    - loc_id: KAOHSIUNG-2
      latitude: 22.6630247
      longitude: 120.3114376

test:
  BIGQUERY_PROJECT: weather-weaver
  BIGQUERY_DATASET: test_forecasts
  BIGQUERY_DAILY_TABLE: daily
  BIGQUERY_HOURLY_TABLE: hourly
  LOCATIONS:
  - loc_id: TAIPEI-1
    latitude: 25.0402779
    longitude: 121.5301837
  - loc_id: KAOHSIUNG-2
    latitude: 22.6630247
    longitude: 120.3114376

production:
  BIGQUERY_PROJECT: weather-weaver
  BIGQUERY_DATASET: forecasts
  BIGQUERY_DAILY_TABLE: daily
  BIGQUERY_HOURLY_TABLE: hourly
  LOCATIONS:
    - loc_id: TAIPEI-1
      latitude: 25.0402779
      longitude: 121.5301837
    - loc_id: TAIPEI-2
      latitude: 25.0457906
      longitude: 121.5439521
    - loc_id: TAIPEI-3
      latitude: 25.0563448
      longitude: 121.5405553
    - loc_id: TAIPEI-4
      latitude: 25.0536751
      longitude: 121.5556621
    - loc_id: TAOYUAN-1
      latitude: 24.9632927
      longitude: 121.2299855
    - loc_id: HSINCHU-1
      latitude: 24.784571
      longitude: 121.018409
    - loc_id: KAOHSIUNG-1
      latitude: 22.5827675
      longitude: 120.3297366
    - loc_id: KAOHSIUNG-2
      latitude: 22.6630247
      longitude: 120.3114376
