---
development:
  BIGQUERY_KEYFILE_JSON: <json key file contents go here>
  DARKSKY_API_URL: <DarkSky Developer Key>
  BIGQUERY_PROJECT: <BigQuery project name>
  BIGQUERY_DATASET: <BigQuery dataset name>
  BIGQUERY_DAILY_TABLE: daily
  BIGQUERY_HOURLY_TABLE: hourly
