---
development:
  BIGQUERY_KEYFILE_JSON: <json key file contents>
  DARKSKY_API_KEY: <darksky api key>

test:
  BIGQUERY_KEYFILE_JSON: <json key file contents>
  DARKSKY_API_KEY: <darksky api key>

production:
  BIGQUERY_KEYFILE_JSON: <json key file contents>
  DARKSKY_API_KEY: <darksky api key>
