---
daily:
  city                        : string
  entered_at                  : timestamp
  latitude                    : float
  longitude                   : float
  offset                      : float
  timezone                    : string
  ahead                       : integer
  time                        : timestamp
  summary                     : string
  icon                        : string
  sunriseTime                 : timestamp
  sunsetTime                  : timestamp
  moonPhase                   : float
  precipIntensity             : float
  precipIntensityMax          : float
  precipIntensityMaxTime      : timestamp
  precipProbability           : float
  precipType                  : string
  temperatureMin              : float
  temperatureMinTime          : timestamp
  temperatureMax              : float
  temperatureMaxTime          : timestamp
  apparentTemperatureMin      : float
  apparentTemperatureMinTime  : timestamp
  apparentTemperatureMax      : float
  apparentTemperatureMaxTime  : timestamp
  dewPoint                    : float
  humidity                    : float
  windSpeed                   : float
  windBearing                 : integer
  visibility                  : string
  cloudCover                  : float
  pressure                    : float
  ozone                       : float

hourly:
  city                        : string
  entered_at                  : timestamp
  latitude                    : float
  longitude                   : float
  offset                      : float
  timezone                    : string
  ahead                       : integer
  time                        : timestamp
  summary                     : string
  icon                        : string
  precipIntensity             : float
  precipProbability           : float
  precipType                  : string
  temperature                 : float
  apparentTemperature         : float
  dewPoint                    : float
  humidity                    : float
  windSpeed                   : float
  windBearing                 : integer
  visibility                  : string
  cloudCover                  : float
  pressure                    : float
  ozone                       : float
